### ISSUE TITLE
Add support for ESLint 9 and according plugins

### ISSUE THREAD

**Issue by klu2** [cloudflightio/cloudflight-eslint-plugin#234]
Please add support for ESLint 9 and also the underlying plugins `@typescript-eslint/eslint-plugin` or `@typescript-eslint/parser` in version `8.1.0`

**Comment by strawberry-choco** [comment]
You can try `1.0.0-rc2` for typescript, Vue and Angular right now. Not everything has been migrated yet, but the most important ones are. Node and React plugins will be migrated soon.

**Comment by strawberry-choco** [comment]
`1.0.0` is released with eslint v9 support.
